export const REQUESTING_LOGIN = 'REQUESTING_LOGIN';

export const FETCHING_TABLES = 'FETCHING_TABLES';
export const FETCHING_TABLES_FAILED = 'FETCHING_TABLES_FAILED';
export const FETCHING_TABLES_SUCCEEDED = 'FETCHING_TABLES_SUCCEEDED';

export const PENDING_TABLES = 'PENDING_TABLES';
export const PENDING_TABLE_SESSIONS = 'PENDING_TABLE_SESSIONS';

export const USER_EMAIL_CHANGED = 'USER_EMAIL_CHANGED';
export const TABLE_SESSIONS_CHANGED = 'TABLE_SESSIONS_CHANGED';
