export const REQUESTING_LOGIN = 'REQUESTING_LOGIN';

export const FETCHING_TABLES = 'FETCHING_TABLES';
export const FETCHING_TABLES_FAILED = 'FETCHING_TABLES_FAILED';
export const FETCHING_TABLES_SUCCEEDED = 'FETCHING_TABLES_SUCCEEDED';

export const PENDING_TABLES = 'PENDING_TABLES';
export const PENDING_TABLE_SESSIONS = 'PENDING_TABLE_SESSIONS';
export const PENDING_REQUEST_TABLE_STATUS_CHANGED = 'PENDING_REQUEST_TABLE_STATUS_CHANGED';

export const USER_EMAIL_CHANGED = 'USER_EMAIL_CHANGED';
export const TABLES_CHANGED = 'TABLES_CHANGED';
export const TABLE_SESSIONS_CHANGED = 'TABLE_SESSIONS_CHANGED';

export const REQUESTING_TABLE_START = 'REQUESTING_TABLE_START';
export const REQUESTING_TABLE_START_FAILED = 'REQUESTING_TABLE_START_FAILED';

export const REQUESTING_TABLE_STOP = 'REQUESTING_TABLE_STOP';
export const REQUESTING_TABLE_STOP_FAILED = 'REQUESTING_TABLE_STOP_FAILED';
export const REQUESTING_TABLE_STOP_SUCCEEDED = 'REQUESTING_TABLE_STOP_SUCCEEDED';

export const CHANGING_TIMER = 'CHANGING_TIMER';
export const TIMER_CHANGED = 'TIMER_CHANGED';
